/**
 * Generates the Card Mode ASCII art: one static glyph per card and a one-turn rotation per card, as
 * depth-cued art (ADR-015).
 *   node scripts/ascii/generate.mts          write src/features/rogue/ascii/*.generated.ts
 *   node scripts/ascii/generate.mts --check  exit 1 if the committed files are stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderAscii } from "../../src/features/rogue/ascii/renderer.ts";
import {
  ANIMATION_FRAMES,
  ANIMATION_PITCH,
  ANIMATION_SIZE,
  ASCII_SCENES,
  animationYaw,
  GLYPH_POSE,
  GLYPH_SIZE,
} from "../../src/features/rogue/ascii/scenes.ts";

const outDir = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../src/features/rogue/ascii",
);
const header =
  "// Generated by scripts/ascii/generate.mts — do not edit. Run `npm run ascii` to regenerate.\n";

const files = new Map<string, string>();

const glyphs = Object.entries(ASCII_SCENES).map(
  ([id, shape]) =>
    `  ${id}: ${JSON.stringify(renderAscii({ shape, ...GLYPH_SIZE, ...GLYPH_POSE }))},`,
);
files.set(
  "glyphs.generated.ts",
  `${header}import type { SectionId } from "@/domain/types";\nimport type { DepthArt } from "./depth";\n\nexport const cardGlyphs: Record<SectionId, DepthArt> = {\n${glyphs.join("\n")}\n};\n`,
);

for (const [id, shape] of Object.entries(ASCII_SCENES)) {
  const frames = Array.from({ length: ANIMATION_FRAMES }, (_, frame) =>
    JSON.stringify(
      renderAscii({
        shape,
        ...ANIMATION_SIZE,
        yaw: animationYaw(frame),
        pitch: ANIMATION_PITCH,
      }),
    ),
  );
  files.set(
    `frames/${id}.generated.ts`,
    `${header}import type { DepthArt } from "../depth";\n\nexport const frames: readonly DepthArt[] = [\n${frames.map((f) => `  ${f},`).join("\n")}\n];\n`,
  );
}

const check = process.argv.includes("--check");
const stale: string[] = [];
for (const [name, content] of files) {
  const path = join(outDir, name);
  if (check) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // missing counts as stale
    }
    if (current !== content) stale.push(name);
  } else {
    writeFileSync(path, content);
  }
}

if (check && stale.length > 0) {
  console.error(`Stale ASCII art (run \`npm run ascii\`): ${stale.join(", ")}`);
  process.exit(1);
}
console.log(check ? "ASCII art up to date." : `Wrote ${files.size} files.`);
