// Generated by scripts/ascii/generate.mts — do not edit. Run `npm run ascii` to regenerate.
import type { SectionId } from "@/domain/types";

export const cardGlyphs: Record<SectionId, string> = {
  about: "                    \n       @@@%%#       \n    %@@@@@%##*+-    \n   #%@@%%%#**+=-:   \n   *#####**+==-::   \n   =+++++==--::::   \n    :----:::::::    \n       ::::::       \n                    ",
  skills: "                    \n       @@@@=:       \n   @@@@@@@@=::::    \n   @@@@@@@@=:::::   \n   @@@@@@@@=:::::   \n   @@@@@#=:::::::   \n    :::::::::::::   \n       ::::::       \n                    ",
  experience: "                    \n                    \n      @@@@%%##      \n   %%##**++===--:   \n  +=-:::    ::::::  \n   :::::=*##*=:::   \n      ::::::::      \n                    \n                    ",
  projects: "                    \n        %%%%        \n      %%%%%%%%      \n     ============   \n    ===========:    \n   ===========:     \n      ======::      \n        ===:        \n                    ",
  education: "                    \n        @@@@@::     \n     @@@@@@@@::     \n     @@@@@@@@::     \n     @@@@@@@@::     \n     @@@@@@@@::     \n     @@@@@@@@::     \n     @+:::::        \n                    ",
  contact: "                    \n         @@@@       \n      @@@@@@@@-     \n     @@@@@@@@@@:    \n    @@@@@@@@@@@:    \n    @@@@@@@@@@:     \n     @@@@@@@::      \n       ::::         \n                    ",
  cv: "                    \n                    \n             :::    \n    :+ @@@@@%::::   \n   @@@%%##*++=:::   \n   *++=-::::: ::    \n    :::             \n                    \n                    ",
};
