"""Markdown renderers for the Manuel Ortiz Portfolio project-memory snapshot.

Every renderer is a pure function of the context dict built by
generate-context.py. Output must be deterministic for a given repository state.
"""

from __future__ import annotations

import re
from collections import defaultdict

TITLE = "Manuel Ortiz Portfolio"
AUTHORITY = "Git working tree > CLAUDE.md > docs/ > this document"


# ------------------------------------------------------------------ helpers

def header(title: str, purpose: str, now: str) -> str:
    return (
        f"# {TITLE} — {title}\n\n"
        f"<!-- generated-at: {now} -->\n"
        f"> Project-memory document. {purpose}\n"
        f"> Authority order: {AUTHORITY}.\n"
        f"> Generated by `scripts/notebooklm/generate-context.py` from repository state. Do not hand-edit.\n\n"
    )


_FENCE = re.compile(r"^\s*(```|~~~)")


def demote_headings(text: str, levels: int = 1) -> str:
    """Push every Markdown heading down so embedded docs nest under ours."""
    out: list[str] = []
    in_fence = False
    for line in text.splitlines():
        if _FENCE.match(line):
            in_fence = not in_fence
        elif not in_fence and line.startswith("#"):
            hashes = len(line) - len(line.lstrip("#"))
            if line[hashes:hashes + 1] in (" ", ""):
                line = "#" * min(hashes + levels, 6) + line[hashes:]
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def embed(c, rel: str) -> str:
    text = c["texts"].get(rel)
    if text is None:
        return f"## `{rel}`\n\n_File not present in the repository._\n\n"
    if not text.strip():
        return f"## `{rel}`\n\n_File is empty._\n\n"
    return f"## Source: `{rel}` (verbatim, headings demoted one level)\n\n{demote_headings(text)}\n"


def dep_version(pkg: dict, name: str) -> str | None:
    for key in ("dependencies", "devDependencies"):
        v = (pkg.get(key) or {}).get(name)
        if v:
            return v
    return None


def deps_matching(pkg: dict, prefix: str) -> list[str]:
    names: set[str] = set()
    for key in ("dependencies", "devDependencies"):
        names.update(n for n in (pkg.get(key) or {}) if n.startswith(prefix))
    return sorted(names)


def has_path(c, prefix: str) -> bool:
    return any(f == prefix or f.startswith(prefix.rstrip("/") + "/") for f in c["files"])


def paths_containing(c, needle: str, roots: tuple[str, ...] = ("src/", "app/", "components/")) -> list[str]:
    return [f for f in c["files"] if f.startswith(roots) and needle in f.lower()]


def stack(c) -> list[tuple[str, str]]:
    pkg = c["package"]
    router = []
    if has_path(c, "app") or has_path(c, "src/app"):
        router.append("App Router")
    if has_path(c, "pages") or has_path(c, "src/pages"):
        router.append("Pages Router")
    ts = "yes (`tsconfig.json`)" if "tsconfig.json" in c["files"] else "no — plain JavaScript"
    rows = [
        ("Next.js", dep_version(pkg, "next") or "(not a dependency)"),
        ("React", dep_version(pkg, "react") or "(not a dependency)"),
        ("Router", " + ".join(router) or "(none detected)"),
        ("TypeScript", ts),
        ("Tailwind CSS", dep_version(pkg, "tailwindcss") or "no"),
        ("Chakra UI", dep_version(pkg, "@chakra-ui/react") or "no"),
        ("Motion / framer-motion",
         " / ".join(f"`{n}` {dep_version(pkg, n)}" for n in ("motion", "framer-motion") if dep_version(pkg, n)) or "no"),
        ("Zustand", dep_version(pkg, "zustand") or "no"),
        ("dnd-kit", ", ".join(deps_matching(pkg, "@dnd-kit/")) or "no"),
        ("Three.js / R3F",
         ", ".join(n for n in ["three", *deps_matching(pkg, "@react-three/")] if dep_version(pkg, n)) or "no"),
        ("Test runner",
         ", ".join(n for n in ("vitest", "jest", "@playwright/test") if dep_version(pkg, n)) or "none"),
    ]
    return rows


def table(rows: list[tuple[str, str]], head: tuple[str, str] = ("Field", "Value")) -> str:
    s = f"| {head[0]} | {head[1]} |\n|---|---|\n"
    for k, v in rows:
        s += f"| {k} | {v} |\n"
    return s + "\n"


def frontmatter_field(text: str, field: str) -> str:
    m = re.search(rf"^{field}:\s*(.+)$", text, re.MULTILINE)
    return m.group(1).strip().strip("'\"") if m else ""


# ----------------------------------------------------------------- doc 00

def doc_00(c) -> str:
    g, pkg = c["git"], c["package"]
    s = header("Project Overview", "Highest-level orientation: what this project is and where it is going.", c["now"])
    s += ("## Purpose\n\n"
          "Professional software-engineering portfolio for Manuel Ortiz. Target design: **two renderers\n"
          "over one typed content model** — **Classic** (fast, readable, SEO/recruiter-optimized) and\n"
          "**Card Mode** (internal name `rogue`; roguelike card-game interaction with an original design\n"
          "language). It is a portfolio, not a browser game: usability, performance, accessibility and\n"
          "professional readability beat visual spectacle.\n\n"
          "The repository currently holds the **legacy** site (see *Stack* below). The migration plan is\n"
          "`docs/Roadmap.md` (mirrored in `20-roadmap.md`); architecture rationale is\n"
          "`docs/architecture.md` (mirrored in `10-architecture.md`). Progress evidence is in\n"
          "`40-roadmap-progress.md`.\n\n")
    s += "## Identity\n\n" + table([
        ("package name", f"`{pkg.get('name', '?')}`"),
        ("Git remote", f"`{g['remote'] or '(none)'}`"),
        ("Git branch", f"`{g['branch']}`"),
        ("Git commit", f"`{g['sha']}` — {g['subject']} ({g['commit_date']})"),
    ])
    s += "## Stack detected in the working tree\n\n" + table(stack(c), ("Concern", "Detected"))
    s += ("## Top-level layout\n\n| Path | Files |\n|---|---|\n")
    for top, n in sorted(c["top_counts"].items()):
        s += f"| `{top}` | {n} |\n"
    s += ("\n## Non-negotiable rules (from `CLAUDE.md`, summarized)\n\n"
          "1. One source of truth for professional content; both renderers consume it.\n"
          "2. Mode (`classic` | `rogue`) is UI state; active section is domain state; switching mode\n"
          "   preserves the active section.\n"
          "3. Sections are deep-linkable by stable hash id (`#projects`); no mode-specific routes.\n"
          "4. Never mount both renderers' expensive runtime simultaneously.\n"
          "5. Three.js / R3F never ship in the critical bundle.\n"
          "6. Drag is never the only way to open a card — click, keyboard and tap always work.\n\n"
          "Full text: `CLAUDE.md` (mirrored in `10-architecture.md`).\n")
    return s


# ----------------------------------------------------------------- doc 10

def doc_10(c) -> str:
    s = header("Architecture and Operating Rules",
               "Verbatim mirror of the architecture documentation, operating rules and ADRs.", c["now"])
    s += embed(c, "CLAUDE.md")
    s += embed(c, "docs/architecture.md")
    adrs = [f for f in c["files"] if f.startswith("docs/adr/") and f.endswith(".md")]
    if adrs:
        for f in adrs:
            s += embed(c, f)
    else:
        s += ("## ADRs\n\n_No `docs/adr/*.md` files exist yet. `docs/Roadmap.md` §6 proposes six ADRs;\n"
              "see `60-decisions.md` for the decisions recorded so far._\n")
    return s


# ----------------------------------------------------------------- doc 20

def doc_20(c) -> str:
    s = header("Roadmap",
               "Verbatim mirror of the phased implementation plan. Progress evidence lives in "
               "`40-roadmap-progress.md`.", c["now"])
    s += embed(c, "docs/Roadmap.md")
    return s


# ----------------------------------------------------------------- doc 30

SOURCE_ROOTS = ("app/", "src/", "pages/", "components/", "lib/", "features/")
ASSET_ROOTS = ("public/",)


def doc_30(c) -> str:
    s = header("Codebase Inventory", "Every source file and asset group in the working tree.", c["now"])
    sizes = c["sizes"]

    s += "## Source files\n\n"
    src = [f for f in c["files"] if f.startswith(SOURCE_ROOTS)]
    if not src:
        s += "_No files under the known source roots._\n\n"
    groups: dict[str, list[str]] = defaultdict(list)
    for f in src:
        groups[f.rsplit("/", 1)[0] if "/" in f else "."].append(f)
    for d in sorted(groups):
        s += f"### `{d}/`\n\n| File | Bytes |\n|---|---|\n"
        for f in groups[d]:
            s += f"| `{f.rsplit('/', 1)[-1]}` | {sizes.get(f, 0)}{' **(empty)**' if sizes.get(f, 0) == 0 else ''} |\n"
        s += "\n"

    s += "## Static assets\n\n| Directory | Files | Extensions |\n|---|---|---|\n"
    assets: dict[str, list[str]] = defaultdict(list)
    for f in c["files"]:
        if f.startswith(ASSET_ROOTS):
            assets[f.rsplit("/", 1)[0]].append(f)
    for d in sorted(assets):
        exts = sorted({f.rsplit(".", 1)[-1].lower() for f in assets[d] if "." in f.rsplit("/", 1)[-1]})
        s += f"| `{d}/` | {len(assets[d])} | {', '.join(exts)} |\n"
    s += "\n"

    s += "## Documentation and tooling files\n\n"
    other = [f for f in c["files"]
             if not f.startswith(SOURCE_ROOTS + ASSET_ROOTS) and not f.startswith(".context/")]
    for f in other:
        s += f"- `{f}` ({sizes.get(f, 0)} B)\n"
    s += "\n"

    pkg = c["package"]
    for key in ("dependencies", "devDependencies"):
        deps = pkg.get(key) or {}
        s += f"## `{key}`\n\n"
        if not deps:
            s += "_none_\n\n"
            continue
        s += "| Package | Spec |\n|---|---|\n"
        for n in sorted(deps):
            s += f"| `{n}` | `{deps[n]}` |\n"
        s += "\n"

    s += ("## Import sites of heavy / fenced libraries\n\n"
          "Rule 5 fences Three.js/R3F out of the critical bundle. These are the files that import them\n"
          "right now:\n\n")
    if c["heavy_imports"]:
        s += "| File | Imports |\n|---|---|\n"
        for f, libs in sorted(c["heavy_imports"].items()):
            s += f"| `{f}` | {', '.join(f'`{l}`' for l in libs)} |\n"
    else:
        s += "_None._\n"
    return s


# ----------------------------------------------------------------- doc 40

def doc_40(c) -> str:
    pkg = c["package"]
    s = header("Roadmap Progress Evidence",
               "Filesystem signals per roadmap phase. Evidence only, never a completion verdict.", c["now"])
    s += ("Each phase in `docs/Roadmap.md` is listed with signals that can be checked mechanically.\n"
          "A satisfied signal means the artefact exists, **not** that the phase's acceptance criteria\n"
          "pass. Phase completion is recorded by hand in `60-decisions.md`, or verified with the\n"
          "`verify-feature` skill.\n\n")

    next_spec = dep_version(pkg, "next") or ""
    m = re.search(r"(\d+)", next_spec)
    next_major = int(m.group(1)) if m else 0
    three_outside = [f for f in c["heavy_imports"] if "/rogue/three/" not in f]

    phases = [
        ("P0 — Repository and baseline", [
            ("`docs/legacy-content/` harvest exists", has_path(c, "docs/legacy-content")),
            (f"Next.js major ≥ 15 (found `{next_spec or 'none'}`)", next_major >= 15),
            ("App Router present (`app/` or `src/app/`)", has_path(c, "app") or has_path(c, "src/app")),
            ("`tsconfig.json` present", "tsconfig.json" in c["files"]),
            ("Tailwind CSS dependency", bool(dep_version(pkg, "tailwindcss"))),
            ("Chakra UI removed", not dep_version(pkg, "@chakra-ui/react")),
            ("CI workflow under `.github/workflows/`", has_path(c, ".github/workflows")),
        ]),
        ("P1 — Domain and content model", [
            ("`src/domain/` or `src/content/` present", has_path(c, "src/domain") or has_path(c, "src/content")),
            ("Test runner dependency (vitest)", bool(dep_version(pkg, "vitest"))),
        ]),
        ("P2 — Shell and Classic Mode", [
            ("Paths mentioning `classic`", bool(paths_containing(c, "classic"))),
        ]),
        ("P3 — Mode system and synchronization", [
            ("Zustand dependency", bool(dep_version(pkg, "zustand"))),
            ("Paths mentioning `mode`", bool(paths_containing(c, "mode"))),
        ]),
        ("P4 — Card Mode static experience", [
            ("Paths mentioning `rogue`", bool(paths_containing(c, "rogue"))),
            ("`motion` dependency", bool(dep_version(pkg, "motion"))),
        ]),
        ("P5 — Lazy loading and preload", [
            ("_Not mechanically detectable — check bundle budgets in CI._", False),
        ]),
        ("P6 — Drag/drop", [
            ("`@dnd-kit/*` dependency", bool(deps_matching(pkg, "@dnd-kit/"))),
        ]),
        ("P7 — Section-specific interactions", [
            ("Paths mentioning `panel`", bool(paths_containing(c, "panel"))),
        ]),
        ("P8 — Optional 3D", [
            ("`@react-three/*` dependency", bool(deps_matching(pkg, "@react-three/"))),
            ("Three.js imported only under `*/rogue/three/`",
             bool(c["heavy_imports"]) and not three_outside),
        ]),
        ("P9 — Performance / a11y hardening", [
            ("_Not mechanically detectable._", False),
        ]),
        ("P10 — Content polish and release", [
            ("_Not mechanically detectable._", False),
        ]),
    ]
    for name, signals in phases:
        s += f"## {name}\n\n"
        for label, ok in signals:
            s += f"- [{'x' if ok else ' '}] {label}\n"
        s += "\n"

    if three_outside:
        s += ("## Rule-5 exposure\n\nThree.js / R3F is imported outside a `rogue/three/` seam:\n\n"
              + "".join(f"- `{f}`\n" for f in sorted(three_outside)) + "\n")
    return s


# ----------------------------------------------------------------- doc 50

CONFIG_FILES = [
    "package.json", "next.config.js", "next.config.mjs", "next.config.ts", "tsconfig.json",
    ".eslintrc.json", "eslint.config.mjs", "prettier.config.js", ".prettierignore",
    "postcss.config.mjs", "vercel.json", ".mcp.json", ".claude/settings.json",
]


def doc_50(c) -> str:
    pkg = c["package"]
    s = header("Build, Deploy and Tooling Config",
               "npm scripts, framework config, CI, deploy target and Claude Code tooling.", c["now"])
    s += "## npm scripts\n\n| Script | Command |\n|---|---|\n"
    for k, v in sorted((pkg.get("scripts") or {}).items()):
        s += f"| `{k}` | `{v}` |\n"
    s += "\n"
    for key in ("homepage", "engines"):
        if key in pkg:
            s += f"- **`{key}`:** `{pkg[key]}`\n"
    s += "\n## Config files\n\n"
    for f in CONFIG_FILES:
        if f == "package.json" or f not in c["texts"]:
            continue
        body = c["texts"][f].rstrip()
        lang = "json" if f.endswith(".json") else ("js" if f.endswith((".js", ".mjs", ".ts")) else "")
        s += f"### `{f}`\n\n```{lang}\n{body}\n```\n\n"

    wf = [f for f in c["files"] if f.startswith(".github/workflows/")]
    s += "## CI workflows\n\n" + ("".join(f"- `{f}`\n" for f in wf) if wf else "_None._\n") + "\n"

    s += "## Claude Code project skills\n\n| Skill | Description |\n|---|---|\n"
    for f in sorted(p for p in c["texts"] if p.startswith(".claude/skills/") and p.endswith("SKILL.md")):
        t = c["texts"][f]
        desc = frontmatter_field(t, "description").replace("|", "\\|")
        if len(desc) > 220:
            desc = desc[:217].rstrip() + "..."
        s += f"| `{frontmatter_field(t, 'name') or f.split('/')[2]}` | {desc} |\n"
    return s


# ----------------------------------------------------------------- doc 90

def doc_90(c) -> str:
    g = c["git"]
    s = header("Current Project State", "Compact snapshot of where the project stands right now.", c["now"])
    s += "## Git\n\n"
    s += f"- **Branch:** `{g['branch']}`\n"
    s += f"- **Commit:** `{g['sha']}`\n"
    s += f"- **Subject:** {g['subject']}\n"
    s += f"- **Commit date:** {g['commit_date']}\n"
    s += f"- **Local branches:** {', '.join(f'`{b}`' for b in g['branches'])}\n"
    tree = "clean" if g["dirty_count"] == 0 else f"{g['dirty_count']} modified/untracked path(s)"
    s += f"- **Working tree:** {tree}\n\n"
    if g["dirty_files"]:
        s += "### Uncommitted paths\n\n" + "".join(f"- `{f}`\n" for f in g["dirty_files"]) + "\n"
    s += "## Recent commits\n\n```\n" + "\n".join(g["recent"]) + "\n```\n\n"
    s += "## Stack right now\n\n" + table(stack(c), ("Concern", "Detected"))
    return s


RENDERERS = {
    "00-project-overview.md": doc_00,
    "10-architecture.md": doc_10,
    "20-roadmap.md": doc_20,
    "30-codebase-inventory.md": doc_30,
    "40-roadmap-progress.md": doc_40,
    "50-build-deploy-config.md": doc_50,
    "90-current-project-state.md": doc_90,
}
